version: "3.8"

services:
  app:
    container_name: fastapi-app-prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "${PRODUCTION_SERVER_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb-prod
    image: mongo
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: