version: "3.8"

services:
  app:
    container_name: fastapi-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/docker_app
    working_dir: /docker_app
    ports:
      - "${DEVELOPMENT_SERVER_PORT}:8000"
    env_file:
      - .env
    environment:
      - PYTHONPAH=/docker_app
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    container_name: mongodb-dev
    image: mongo
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
