version: "3.8"

services:
  app:
    container_name: fastapi-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/docker_app
    working_dir: /docker_app
    ports:
      - "${PRODUCTION_SERVER_PORT}:8000"
    env_file:
      - .env
    environment:
      - PYTHONPAH=/app
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb-dev
    image: mongo
    env_file:
      - .env
