services:
  app:
    container_name: fastapi-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /docker_app
    ports:
      - "${DEVELOPMENT_SERVER_PORT}:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/docker_app
    depends_on:
      - mongodb
      - redis
      - celery-worker
    networks:
      - app-network
    volumes:
      - .:/docker_app

  mongodb:
    container_name: mongodb-dev
    image: mongo
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    container_name: celery_worker
    working_dir: /docker_app
    command: celery -A app.services.scheduler worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/docker_app
      # setting time the same as on the machine, where container was built
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network

  flower:
    image: mher/flower
    environment:
      - FLOWER_BROKER=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
