name: CI - Build the application in a Docker container and run tests

# Triger an event when:
#   1. Push is made to a dev branch
#   2. Pull Request is made to a dev branch
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build Application from Dockerfile
    runs-on: ubuntu-latest

  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand('ping')'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5s

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          MONGODB_URL: mongodb://localhost:27017
        run: |
          pytest --maxfail=1 --disable-warnings

