name: CI pipeline -- build and test application

# Triger an event when:
#   1. Push is made to a dev branch
#   2. Pull Request is made to a dev branch
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test_application:
    name: Build Application from Dockerfile
    runs-on: ubuntu-latest

    steps:
      # pulling code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # preparing an environment for Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # loging in to the GitHub container registry
      # not necessary for this moment of time
      # but might come in handy in the future
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # installing python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # installing docker-compose
      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      # this one will run a full CI process from the Makefile:
      # building and running a container, then, running tests and shutting down a container
      - name: Run CI process
        run: sudo make ci
